import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Sidebar used by the schedule docs (Home/Turma/Professor/Sala + Campus info)
  schedulelSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Home',
      className: 'scheduleItem scheduleItem--home',
    },
    {
      type: 'category',
      label: 'Turma',
      className: 'scheduleItem scheduleItem--turma',
      items: [{type: 'autogenerated', dirName: 'turma'}],
    },
    {
      type: 'category',
      label: 'Professor',
      className: 'scheduleItem scheduleItem--professor',
      items: [{type: 'autogenerated', dirName: 'professor'}],
    },
    {
      type: 'category',
      label: 'Sala',
      className: 'scheduleItem scheduleItem--sala',
      items: [{type: 'autogenerated', dirName: 'sala'}],
    },

    // Spacer to push the Campus section to the bottom of the sidebar.
    // The UL is turned into a flex column in `src/css/custom.css`.
    {
      type: 'html',
      value: '<div class="sidebarFlexSpacerInner"></div>',
      defaultStyle: true,
      className: 'sidebarFlexSpacer',
    },

    {
      type: 'html',
      value: '<div class="sidebarSectionTitle">INFORMAÇÕES DO CAMPUS</div>',
      defaultStyle: true,
      className: 'campusInfoGroupTitle',
    },
    {
      type: 'doc',
      id: 'campus/administracao',
      label: 'Administração',
      className: 'campusInfoItem campusInfoItem--administracao',
    },
    {
      type: 'doc',
      id: 'campus/setor-de-saude',
      label: 'Setor de Saúde',
      className: 'campusInfoItem campusInfoItem--saude',
    },
    {
      type: 'category',
      label: 'Cursos',
      collapsible: true,
      collapsed: true,
      className: 'campusInfoItem campusInfoItem--cursos',
      items: [
        {
          type: 'category',
          label: 'Técnico',
          collapsible: true,
          collapsed: true,
          className: 'campusCourseType campusCourseType--tecnico',
          items: [
            {type: 'doc', id: 'cursos/tecnico-administracao-integrado', label: 'Administração (Integrado)'},
            {type: 'doc', id: 'cursos/tecnico-eventos-integrado', label: 'Eventos (Integrado)'},
            {type: 'doc', id: 'cursos/tecnico-informatica-integrado', label: 'Informática (Integrado)'},
            {type: 'doc', id: 'cursos/tecnico-administracao-subsequente', label: 'Administração (Subsequente)'},
            {type: 'doc', id: 'cursos/tecnico-gastronomia-subsequente', label: 'Gastronomia (Subsequente)'},
            {type: 'doc', id: 'cursos/tecnico-guia-de-turismo-subsequente', label: 'Guia de Turismo (Subsequente)'},
            {
              type: 'doc',
              id: 'cursos/tecnico-servico-de-restaurante-e-bar',
              label: 'Serviço de Restaurante e Bar (Subsequente)',
            },
            {type: 'doc', id: 'cursos/tecnico-gastronomia-proeja', label: 'Gastronomia (PROEJA)'},
          ],
        },
        {
          type: 'category',
          label: 'Licenciatura',
          collapsible: true,
          collapsed: true,
          className: 'campusCourseType campusCourseType--licenciatura',
          items: [
            {type: 'doc', id: 'cursos/licenciatura-fisica', label: 'Licenciatura em Física'},
            {type: 'doc', id: 'cursos/licenciatura-matematica', label: 'Licenciatura em Matemática'},
          ],
        },
        {
          type: 'category',
          label: 'Tecnologia',
          collapsible: true,
          collapsed: true,
          className: 'campusCourseType campusCourseType--tecnologia',
          items: [
            {type: 'doc', id: 'cursos/tecnologia-gastronomia', label: 'Gastronomia'},
            {type: 'doc', id: 'cursos/tecnologia-sistemas-para-internet', label: 'Sistemas para Internet'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contato',
      collapsible: true,
      collapsed: true,
      className: 'campusInfoItem campusInfoItem--contato',
      items: [
        {
          type: 'html',
          value:
            '<div class="campusInfoSubItem campusInfoSubItem--telefone"><span class="campusInfoSubItem__label">Telefone</span><span class="campusInfoSubItem__value">(89) 2221-9904</span></div>',
          defaultStyle: true,
        },
        {
          type: 'html',
          value:
            '<div class="campusInfoSubItem campusInfoSubItem--endereco"><span class="campusInfoSubItem__label">Endereço</span><span class="campusInfoSubItem__value">BR 020, S/N, Bairro Primavera, São Raimundo Nonato - PI, CEP 64770-000</span></div>',
          defaultStyle: true,
        },
      ],
    },
  ],
};

export default sidebars;

